services:
    profiler:
        public: true
        class: Symfony\Component\HttpKernel\Profiler\Profiler
        arguments:
            - '@profiler.storage'

    profiler.storage:
        class: Symfony\Component\HttpKernel\Profiler\FileProfilerStorage
        arguments:
            - 'file:%kernel.cache_dir%/profiler'

    profiler.listener:
        class: Symfony\Component\HttpKernel\EventListener\ProfilerListener
        arguments:
            - '@profiler'
            - '@request_stack'
            #- '@request.matcher'
        tags:
            - { name: kernel.event_subscriber }

    profiler.data_collector.time:
        class: Gestione\Component\Profiler\DataCollector\TimeDataCollector
        arguments:
            - '@kernel'
            - '@stopwatch'
        tags: [ 'profiler.data_collector' ]

    profiler.data_collector.event:
        class: Symfony\Component\HttpKernel\DataCollector\EventDataCollector
        arguments:
            - '@event_dispatcher'
        tags: [ 'profiler.data_collector' ]

    profiler.data_collector.request:
        class: Symfony\Component\HttpKernel\DataCollector\RequestDataCollector
        tags: [ 'profiler.data_collector' ]

    profiler.data_collector.router:
        class: Symfony\Component\HttpKernel\DataCollector\RouterDataCollector
        tags: [ 'profiler.data_collector' ]

    profiler.data_collector.config:
        class: Symfony\Component\HttpKernel\DataCollector\ConfigDataCollector
        tags: [ 'profiler.data_collector' ]

    profiler.data_collector.exception:
        class: Symfony\Component\HttpKernel\DataCollector\ExceptionDataCollector
        tags: [ 'profiler.data_collector' ]

    profiler.data_collector.logger:
        class: Symfony\Component\HttpKernel\DataCollector\LoggerDataCollector
        tags: [ 'profiler.data_collector' ]

    profiler.data_collector.memory:
        class: Symfony\Component\HttpKernel\DataCollector\MemoryDataCollector
        tags: [ 'profiler.data_collector' ]

    stopwatch:
        class: Symfony\Component\Stopwatch\Stopwatch
