<?php

namespace Gestione\Cms\Content\Page;

use DateTime;
use Gestione\Component\I18n\LocaleInterface;

interface PageInterface
{
    public static function fromArray(array $data): PageInterface;
    public function toArray(): array;
    public function getId(): string;
    public function setId($id);
    public function getType();
    public function setType($type);
    public function getStatus();
    public function setStatus($status);
    public function getPublishedAt(): DateTime;
    public function setPublishedAt(DateTime $publishedAt);
    public function getCreatedAt(): DateTime;
    public function setCreatedAt(DateTime $createdAt);
    public function getUpdatedAt(): DateTime;
    public function setUpdatedAt(DateTime $updatedAt);
    public function getLocale(): LocaleInterface;
    public function setLocale(LocaleInterface $locale);
    public function getTitle();
    public function setTitle($title);
    public function getSlug();
    public function setSlug($slug);
    public function getIntroduction();
    public function setIntroduction($introduction);
    public function getContent();
    public function setContent($content);
    public function getVisibility();
    public function setVisibility($visibility);
    public function getAutogeneratedLocale();
    public function setAutogeneratedLocale($autogeneratedLocale);
}
